name: run ui_test.py

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to GitHub runner

      - name: Install Chrome browser
        run: sudo apt install chromium-browser

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run test script

        run: pytest --html=report.html --self-contained-html

          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: report.html
            retention-days: 5